version: '3.7'
services:
  db:
    image: postgres:latest
    container_name: go-postgresql
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      